import service from '@/utils/request'
export const getMenu = (data) => service({ url: '/v2/system/menu/tree', method: 'get' })
export const getMenuList = (data) => service({ url: '/v2/system/menu/tree', method: 'get' })
export const asyncMenu = () => service({ url: '/v2/system/menu/tree', method: 'get' })
export const getBaseMenuTree = () => service({ url: '/v2/system/menu/tree', method: 'get' })
export const addBaseMenu = (data) => service({ url: '/v2/system/menu', method: 'post', data })
export const deleteBaseMenu = (data) => service({ url: `/v2/system/menu/${data.id||data.ID}`, method: 'delete' })
export const updateBaseMenu = (data) => service({ url: '/v2/system/menu', method: 'post', data })
export const getBaseMenuById = (data) => service({ url: `/v2/system/menu/${data.id||data.ID}`, method: 'get' })
export const addMenuAuthority = (data) => service({ url: '/v2/system/menu/authority', method: 'post', data })
export const getMenuAuthority = (data) => service({ url: `/v2/system/menu/tree?authorityId=${data.authorityId}`, method: 'get' })
