import service from '@/utils/request'
export const login = (data) => service({ url: '/v2/login', method: 'post', data })
export const getUserInfo = () => service({ url: '/v2/system/auth/me', method: 'get' })
export const getUserList = (data) => service({ url: '/v2/system/user/list', method: 'get', params: data })
export const changePassword = (data) => service({ url: '/v2/system/user/password', method: 'post', data })
export const setUserInfo = (data) => service({ url: '/v2/system/user/profile', method: 'put', data })
export const setSelfInfo = (data) => service({ url: '/v2/system/user/profile', method: 'put', data })
export const register = (data) => service({ url: '/v2/system/user', method: 'post', data })
export const deleteUser = (data) => service({ url: `/v2/system/user/${data.id||data.ID}`, method: 'delete' })
export const setUserAuthorities = (data) => service({ url: `/v2/system/user/${data.ID||data.id}/authorities`, method: 'put', data: {authorityIds: data.authorityIds} })
export const resetPassword = (data) => service({ url: `/v2/system/user/${data.ID||data.id}/reset-password`, method: 'post', data: {password: data.password||data.Password} })
export const setUserAuthority = (data) => service({ url: `/v2/system/user/${data.id||data.ID}/authorities`, method: 'put', data: {authorityIds: [data.authorityId]} })
export const setSelfSetting = () => service({ url: '/v2/system/user/profile', method: 'put', data: {} })
export const captcha = () => service({ url: '/base/captcha', method: 'post' })
